[package]
name = "wpc"
version = "0.1.0"
authors = ["Jagadeesh Kotra <jagadeesh@stdin.top>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = "1.0.104"
serde_json = "1.0.48"
reqwest = { version = "0.10", features = ["blocking", "json"] }
clap = {version = "2.33", features = ["yaml"]}
rand = "0.7"
chrono = "0.4.10"
os_info = "2.0.1"
whoami = "0.8.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
