[package]
name = "wpc"
version = "1.0.0"
authors = ["Jagadeesh Kotra <jagadeesh@stdin.top>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = "1.0.104"
serde_json = "1.0.48"
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = {version = "2.33", features = ["yaml"]}
rand = "0.7"
chrono = "0.4.10"
enquote = "1.0.3"
dirs = "2.0.2"
image = "0.23.12"
tokio = { version = "1", features = ["full"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
winreg = "0.7.0"
