steps:
  # Install Rust using rustup
  - name: "rust:latest"
    id: "Install Rust"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        rustup update
        rustc --version
        cargo --version

  # Cache dependencies
  - name: "rust:latest"
    id: "Cache Dependencies"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cargo fetch

  # Build the project
  - name: "rust:latest"
    id: "Build"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cargo build --release

  # Run tests
  - name: "rust:latest"
    id: "Test"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace
        cargo test --release --verbose --target-dir=/workspace/target

timeout: "1200s"  # Set timeout (20 minutes)

# Specify the Rust version (optional)
options:
  env:
    - 'RUSTUP_TOOLCHAIN=stable'
  logging: CLOUD_LOGGING_ONLY