steps:
  # Use Debian as the base image
  - name: "debian:latest"
    id: "Install Rust & Python"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apt update && apt install -y curl python3 python3-pip python3-venv
        ln -sf /usr/bin/python3 /usr/bin/python
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.profile
        source ~/.profile
        rustup update
        rustc --version
        cargo --version
        which python

  # Run tests
  - name: "debian:latest"
    id: "Run Tests"
    entrypoint: "sh"
    env:
      - "GCP_CLOUD_BUILD=1"
    args:
      - "-c"
      - |
        source ~/.profile
        cd /workspace
        cargo test --verbose --target-dir=/workspace/target -- --nocapture

timeout: "1200s"  # Set timeout (20 minutes)

# Specify the Rust version (optional)
options:
  env:
    - 'RUSTUP_TOOLCHAIN=stable'
  logging: CLOUD_LOGGING_ONLY
