steps:
  # Install Rust using rustup
  - name: "rust:latest"
    id: "Install & Update Rust"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        rustup update
        apt update && apt install -y python3 python3-pip python-is-python3
        rustc --version
        cargo --version

  # Run tests
  - name: "rust:latest"
    id: "Test"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace
        cargo test --verbose --target-dir=/workspace/target

timeout: "1200s"  # Set timeout (20 minutes)

# Specify the Rust version (optional)
options:
  env:
    - 'RUSTUP_TOOLCHAIN=stable'
  logging: CLOUD_LOGGING_ONLY