steps:
  # Step 1: Install Rust
  - name: 'rustlang/rust:latest'
    id: 'Install Rust'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'

  # Step 2: Set up Rust environment
  - name: 'rustlang/rust:latest'
    id: 'Set up Rust environment'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'source $HOME/.cargo/env'

  # Step 3: Build the Rust project
  - name: 'rustlang/rust:latest'
    id: 'Build Rust project'
    entrypoint: 'cargo'
    args:
      - 'build'
      - '--release'

  # Step 4: Run tests
  - name: 'rustlang/rust:latest'
    id: 'Run tests'
    entrypoint: 'cargo'
    args:
      - 'test'

# Timeout for the build (optional)
timeout: '1200s'

# Specify the Rust version (optional)
options:
  env:
    - 'RUSTUP_TOOLCHAIN=stable'